### ISSUE TITLE
Have you ever implemented your method in efficientnet network?

### ISSUE THREAD

**Issue by yucathy** [alexandrosstergiou/SoftPool#29]
Hi, thank you for your great idea. It's very interesting.

Because efficientnet get a lot of great results in Imagenet.
I just want to know have you ever implemented your idea in efficientnet before?
(Because efficientnet get a lot of great results in Imagenet.)

If you had done it before, What's the result?

Thank you again for everything you've done.

**Comment by alexandrosstergiou** [comment]
Hi @yucathy ,

Thank you for your interest. We have not performed any experiments on architectures such as EfficientNets or MobileNets because, in contrast to other models (ResNets, DenseNets etc.), they do not include pooling layers (only for vectorisation with GlobAvg which is a special case). You could possibly incorporate Softool at the first convolution by also increasing the input size (224 -> 448 for example). 

One more recently introduced family of networks that SoftPool can be used with are RegNets (Radosavovic \text{et al.} 2020) which are based on ResNets. We have not experimented with them however.

Best,
Alex

**Comment by yucathy** [comment]
Hi @alexandrosstergiou ,

It's a nice work and good news for us to try.

Thank you for your response.

**Comment by alexandrosstergiou** [comment]
Will close this due to inactivity. Feel free to open a new issue for other questions/problems.

Best,
Alex
