### ISSUE TITLE
afterimages in the video

### ISSUE THREAD

**Issue by shuaizzZ** [alexandrosstergiou/SoftPool#3]
Why are there obvious afterimages in the video processing results?

**Comment by alexandrosstergiou** [comment]
@shuaizzZ Afterimages are produced because pooling is applied spatio-temporally, so multiple frames are fused together to single frames. This is present with every type of pooling method (e.g. average, max etc.) that is not tailored to handle spatio-temporal data. However, in contrast to Average and Maximum pooling, we noticed this effect was minimized with SoftPool (more examples shown in the supplementary material [in our paper](https://arxiv.org/pdf/2101.00440.pdf)).

Best,
Alex
