### ISSUE TITLE
Have some trouble in "make install"

### ISSUE THREAD

**Issue by MikeShuang96** [alexandrosstergiou/SoftPool#37]
Hi,I have trouble in "make install". The detail:FAILED: /pytorch/build/temp.linux-x86_64-3.6/CUDA/softpool_cuda_kernel.o
#pragma omp parallel for if ((end - begin) >= grain_size)
^
ninja: build stopped: subcommand failed.
python3.6/subprocess.py", line 438, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
RuntimeError: Error compiling objects for extension
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
Could you please help me?

**Comment by alexandrosstergiou** [comment]
Hi @MikeShuang96,

The `RuntimeError` shows some type of failure during the build. One option is to use a log during the build to get the proper error message.

However, since the error is related to `ninja` another option could also be to try and build the repo without `ninja`. i.e. replace [line 19 in setup.py](https://github.com/alexandrosstergiou/SoftPool/blob/70e7b3b51640b9abd34103f7b68990c5ef6aa2f8/pytorch/setup.py#L19) with: `'build_ext' : BuildExtension.with_options(use_ninja=False)`.
