### ISSUE TITLE
sfotpool instead of convolution in YOLO

### ISSUE THREAD

**Issue by xiaoyi-creator** [alexandrosstergiou/SoftPool#42]
I want to use sfotpool instead of convolution in YOLO to complete image downsampling, but I don’t know whether to use 1D, 2D or 3D. Can you give me some suggestions?

**Comment by alexandrosstergiou** [comment]
Hi @xiaoyi-creator,

If you are using 2D Convolutions I suppose you could `SoftPool2d`. Do note that you will be basically just downsampling if you do that, so you might want to still use 2D Convolutions but also maintain the spatial dimension. You could then use SoftPool to spatially downsample them. This way you can still have a learnable part in your downsampling.

There are many options ofc since is up to you and how you would like to introduce SoftPool in your project.
